# Generated by Django 5.2.5 on 2025-08-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PartnerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="Razão social"),
                ),
                ("cnpj", models.CharField(max_length=32, verbose_name="CNPJ")),
                (
                    "legal_representative",
                    models.CharField(
                        max_length=120, verbose_name="Representante legal"
                    ),
                ),
                (
                    "role",
                    models.CharField(blank=True, max_length=120, verbose_name="Cargo"),
                ),
                ("phone", models.CharField(max_length=50, verbose_name="Telefone")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "participation_type",
                    models.CharField(
                        choices=[
                            (
                                "contratante_pcd",
                                "Empresa contratante de jovem aprendiz PcD",
                            ),
                            (
                                "apoio_divulgacao",
                                "Empresa apoiadora com recursos ou divulgação",
                            ),
                            (
                                "capacitacao_inclusao",
                                "Empresa interessada em capacitação sobre inclusão",
                            ),
                        ],
                        max_length=32,
                        verbose_name="Deseja participar como",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, verbose_name="Mensagem (opcional)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
